### ISSUE TITLE
Printing is very light

### ISSUE THREAD

**Issue by za3k** [rbaron/catprinter#72]
All images are printed with no dithering in `-t` mode. On the left is a color image of a frog. In the center is a test all-black image. On the right is a test page the printer auto-printed when it turned on.

![PXL_20230422_224138701 MP-crop](https://user-images.githubusercontent.com/726482/233810828-f02c66e7-e00b-49d0-a753-ba2bf16d4e5d.jpg)

**Comment by jonkpirateboy** [comment]
I have the same problem :/
Did you find a solution @za3k?

**Comment by ashbork** [comment]
Seconding this, I've had better results with other tools so that **should** be possible. It looks like we're not touching the thermal strength at all. The `-t` option also seems like sort of a noop? 
The [PRINTER_MODE](https://github.com/rbaron/catprinter/blob/a5e00c80c2ced94884bdf8da7a9ba0eef2f9db2c/catprinter/cmds.py#L172) constant isn't used and we're not using `cmd_set_energy` either. (Adding the constant to the data array seems to worsen the issue when not in dark mode, too)

**Comment by za3k** [comment]
@jonkpirateboy Nope. If I had a solution, I would have posted it. I no longer use the printer, this bug was reported in 2023.

(FYI it's very **mildly** rude to respond to a bug with nothing past "I have this bug too", because potentially everyone in the thread gets notification. Instead, it's common on github to just add a little :+1: at the bottom. No notifications, and the thread is easier to read.

Of course, if you have a workaround or a fix that's a different story!)

**Comment by rbaron** [comment]
I had some time to reanimate my cat printer today and found a fix for the light printing. If anyone is willing to help me test it, let me know in #78. Tks!
